# Generated by Django 2.1.7 on 2019-02-27 21:36

import campaigns.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Campaign name...', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='Campaign description...')),
                ('slug', models.IntegerField(default=campaigns.models.Campaign.random_code, unique=True)),
                ('members', models.ManyToManyField(related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
