# Generated by Django 2.1.7 on 2019-03-04 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='now',
        ),
        migrations.AddField(
            model_name='campaign',
            name='expiration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
