# Generated by Django 2.1.7 on 2019-03-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20190304_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='members',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='numbermembers',
        ),
    ]
