# Generated by Django 2.1.7 on 2019-03-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190304_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='campaign',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
