# Generated by Django 2.1.7 on 2019-03-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20190324_0243'),
        ('accounts', '0003_auto_20190306_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='campaign', to='campaigns.Campaign'),
            preserve_default=False,
        ),
    ]
